---
# - name: Log into private registry and force re-authorization
#   docker_login:
#     registry: docker.io
#     username: karthiknamburu
#     password: Usa@2013
#     reauthorize: yes
#   sudo: true

#- name: Pull  Rancher/server image
 # command: docker Pull rancher/server:latest

# - name: run the Rancher/server contianer
#   command: docker run -d -p "{{ rancher_port }}:8080" rancher/server:latest

- name: Pull and run the Rancher/server contianer
  docker:
      name: "{{ rancher_name }}"
      image: rancher/server:latest
      restart_policy: always
      ports: 
        - "{{ rancher_port }}:8080"
      # proxy:
      #   - https://10.243.128.27:8080'
  #environment: '{{http_proxy}}'


- wait_for: delay=30

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ ansible_default_ipv4.address }}:{{ rancher_port }}"